name: CI - Train and Save the Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  model_training:
    name: Trains and Save the Model
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11, 3.12]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade Pip
        run: pip install --upgrade pip setuptools wheel

      - name: Install Project Dependencies
        run: pip install -r requirements.txt

      - name: Train the Model
        run: |
          python train_model.py
          ls -la artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts-${{ matrix.python }}-${{ github.run_id }}
          path: artifacts